### ISSUE TITLE
Why you exclude ext directory?

### ISSUE THREAD

**Issue by nkt** [marcqualie/hoard-utils#3]
You should not do that. Zephir generates C code, you can compile it's anywhere you want, without Zephir itself.

**Comment by marcqualie** [comment]
If I included the C code then I'd have to re-commit that everytime I changed the .zep files which isn't a great workflow since it's technically generated code which should be handled by a build system and not commited into source control.

Take a pull request for example:
1. User X submits a pull request that modifies the .zep files.
2. I accept the merge into master
3. I pull the code locally
4. I recompile the C code to make sure it's up to date with the latest merge
5. I push back to master
6. The C code and .zep files are in sync

If I ignore the C code
1. User X submits a pull request that modifies the .zep files
2. I acccept  the merge into master
3. The files are in sync because they are generated from the raw .zep files

I understand why it could be useful to have the C files in the repository but since they are auto generated by a program it's generally good practice to ignore them and build them using the compiler each time.

I'm open for suggestions on how to keep the .zep files and C code in sync if you have any?

**Comment by nkt** [comment]
I fully accept your logic, and it's works with frontend files, like css or js.
Maybe you're right, so you can attach build with next release on github. But for now - Zephir under development, and not ready for production, so it's will be cool to see generated code inside repository, without compilation.
PS Also zephir generates different code if you have `ext-gmp` or not.
